function AdminUI.OpenDeveloperTools()
    local page = AdminUI.RegisterPage('developer_tools')
    AdminUI.AddHeader(page, AdminTranslate('admin_header'), AdminTranslate('developer_tools_header'))
    local inspectorLabel = AdminTranslate('entity_inspector')
    AdminUI.AddButton(page, AdminUI.GetToggleLabel(inspectorLabel, 'entity_inspector'), function(_, element)
        AdminUI.RunToggleAction(inspectorLabel, 'entity_inspector', element, AdminDeveloperTools.ToggleDevGun)
    end)
    local boneLabel = AdminTranslate('bone_viewer')
    AdminUI.AddButton(page, AdminUI.GetToggleLabel(boneLabel, 'bone_viewer'), function(_, element)
        AdminUI.RunToggleAction(boneLabel, 'bone_viewer', element, AdminDeveloperTools.ToggleBoneDisplay)
    end)
    AdminUI.AddFooter(page)
    AdminUI.AddFooterButton(page, AdminTranslate('back'), AdminUI.OpenMain)
    AdminUI.OpenPage('developer_tools')
end
