function AdminUI.OpenTeleports()
    local page = AdminUI.RegisterPage('teleports')
    AdminUI.AddHeader(page, AdminTranslate('admin_header'), AdminTranslate('teleport_header'))
    local waypointLabel = AdminTranslate('teleport_to_waypoint')
    AdminUI.AddButton(page, waypointLabel, function()
        AdminUI.RunAction(waypointLabel, AdminTeleports.ToWaypoint)
    end)
    local autoLabel = AdminTranslate('toggle_auto_waypoint')
    AdminUI.AddButton(page, AdminUI.GetToggleLabel(autoLabel, 'auto_waypoint'), function(_, element)
        AdminUI.RunToggleAction(autoLabel, 'auto_waypoint', element, AdminTeleports.ToggleAutoWaypoint)
    end)
    AdminUI.AddFooter(page)
    AdminUI.AddFooterButton(page, AdminTranslate('back'), AdminUI.OpenMain)
    AdminUI.OpenPage('teleports')
end
