-- Default numeric staff tiers:
-- 50 = Moderator, 75 = Senior Admin, 99 = Owner.
-- Change the numbers to match the levels in your server's roles table.
Config.permissions = {
    ['roles.assignment.manage'] = 99,
    ['menu.open'] = 50,
    ['server.overview'] = 50,
    ['server.announce'] = 75,
    ['players.view'] = 50,
    ['player.info'] = 50,
    ['player.go_to'] = 50,
    ['player.bring'] = 50,
    ['player.send_back'] = 50,
    ['player.spectate'] = 50,

    ['moderation.view'] = 50,
    ['moderation.bans.view'] = 75,
    ['moderation.search'] = 50,
    ['moderation.search_identifiers'] = 75,
    ['moderation.history'] = 50,
    ['moderation.warn'] = 50,
    ['moderation.ban'] = 75,
    ['moderation.unban'] = 75,
    ['moderation.kick'] = 50,

    ['reports.view'] = 50,
    ['reports.claim'] = 50,
    ['reports.close'] = 50,
    ['reports.manage'] = 75,

    ['cases.view'] = 50,
    ['cases.create'] = 50,
    ['cases.claim'] = 50,
    ['cases.link'] = 50,
    ['cases.close'] = 75,
    ['cases.manage'] = 75,

    ['notes.view'] = 50,
    ['notes.create'] = 50,
    ['notes.edit'] = 75,
    ['notes.archive'] = 75,
    ['notes.history'] = 75,

    ['audit.view'] = 75,
    ['audit.sensitive'] = 99,

    ['staff.view'] = 99,
    ['staff.search'] = 99,
    ['staff.search_identifiers'] = 99,
    ['staff.history'] = 99,
    ['staff.role.assign'] = 99,

    ['economy.dollars.add'] = 99,
    ['economy.dollars.remove'] = 99,
    ['economy.gold.add'] = 99,
    ['economy.gold.remove'] = 99,
    ['economy.tokens.add'] = 99,
    ['economy.tokens.remove'] = 99,
    ['economy.xp.add'] = 99,
    ['economy.xp.remove'] = 99,
    ['character.restore_model'] = 75,
    ['inventory.give'] = 75,
    ['inventory.inspect'] = 50,
    ['inventory.remove'] = 75,
    ['inventory.manage'] = 75,
    ['weapons.issue'] = 99,
    ['weapons.ammo.grant'] = 75,

    ['booster.invincibility'] = 75,
    ['booster.invisibility'] = 75,
    ['booster.infinite_stamina'] = 75,
    ['booster.heal'] = 50,
    ['booster.revive'] = 50,
    ['booster.kill'] = 75,
    ['booster.disable_fow'] = 75,
    ['booster.noclip'] = 75,
    ['ped.change'] = 75,

    ['developer.entity_inspector'] = 75,
    ['developer.bone_viewer'] = 75,
    ['developer.copy_coordinates'] = 50,

    ['teleport.waypoint'] = 50,
    ['teleport.auto_waypoint'] = 50,
    ['teleport.coordinates'] = 50,

    ['troll.lightning_strike'] = 99,
    ['troll.freeze'] = 75,
    ['troll.teleport_to_heaven'] = 99,
    ['troll.cage'] = 75,
    ['troll.force_cinematic_camera'] = 75,
    ['troll.make_ped_giant'] = 99,
    ['troll.hostile_ped_army'] = 99,
    ['troll.handcuff'] = 75,
    ['troll.kick_from_vehicle'] = 75,
    ['troll.hostile_bear'] = 99,
    ['troll.lag'] = 99
}
